# Generated by Django 3.0.3 on 2020-03-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula8', '0002_auto_20200307_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='ativo',
            field=models.BooleanField(default=True, help_text='ativo ou inativo'),
        ),
    ]
