# Generated by Django 3.0.3 on 2020-02-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula5', '0003_carrinho_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
