# Generated by Django 3.0.3 on 2020-03-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoDestinatario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(blank=True)),
                ('logradouro', models.TextField(max_length=500)),
                ('numero', models.TextField(max_length=10)),
                ('bairro', models.TextField(max_length=50)),
                ('cidade', models.TextField(max_length=100)),
                ('uf', models.TextField(max_length=2)),
                ('nome_destinatario', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnderecoRemetente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deletado_em', models.DateTimeField(blank=True)),
                ('logradouro', models.TextField(max_length=500)),
                ('numero', models.TextField(max_length=10)),
                ('bairro', models.TextField(max_length=50)),
                ('cidade', models.TextField(max_length=100)),
                ('uf', models.TextField(max_length=2)),
                ('nome_remetente', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
